import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// BB 2021 - Prova A (Agente Comercial) - Batch 3: Q31-Q70
const questionsData = [
    { numero: 31, materia: "Conhecimentos Bancários", enunciado: "Um consultor financeiro capta clientela para investir em instituição financeira. É informado de que um dos indivíduos estaria realizando operações de aportes de recursos de valores elevados para o seu perfil e foi oferecido um empréstimo para dar suporte. A situação narrada fere a ética bancária, pois o consultor", alternativa_A: "tem como função principal maximizar os lucros da instituição financeira.", alternativa_B: "precisa obter a autorização do seu contato para oferecer um empréstimo.", alternativa_C: "está indiretamente facilitando operações que podem ser consideradas ilegais, como a lavagem de dinheiro.", alternativa_D: "deve alertar o cliente para que não faça aportes de valores elevados.", alternativa_E: "atua como intermediário e não é responsável pelas operações dos clientes.", gabarito: "C" },
    { numero: 32, materia: "Conhecimentos Bancários", enunciado: "A partir de 2020, com a pandemia da Covid-19 e o aumento das incertezas quanto à recuperação da economia global, o real brasileiro sofreu uma forte desvalorização. De acordo com o texto da prova, essa desvalorização foi causada", alternativa_A: "pela queda da taxa de juros interna, que atraiu capitais estrangeiros.", alternativa_B: "pela apreciação do real em relação ao dólar.", alternativa_C: "pela desvalorização do dólar no mercado internacional.", alternativa_D: "pela valorização das commodities.", alternativa_E: "pelo aumento das incertezas quanto à recuperação da economia global, que intensificou a saída de moeda estrangeira.", gabarito: "E" },
    { numero: 33, materia: "Conhecimentos Bancários", enunciado: "A reversão da entrada de capitais, a partir de 2017, e a subsequente saída de moeda estrangeira do Brasil foram influenciadas", alternativa_A: "pela elevação da taxa de juros internacional, com o fim da política de juros zero nos EUA.", alternativa_B: "pela crise econômica brasileira de 2014-2016.", alternativa_C: "pela desvalorização do real, que tornou ativos brasileiros mais baratos.", alternativa_D: "pela estabilidade da economia global.", alternativa_E: "pela intervenção do Banco Central no mercado de câmbio.", gabarito: "A" },
    { numero: 34, materia: "Conhecimentos Bancários", enunciado: "Uma empresa utiliza um processo de auditoria interna para garantir a confiabilidade de seus relatórios. A decisão de investir em um novo sistema automatizado para reduzir riscos de erros e fraudes está alinhada ao princípio de Governança Corporativa de", alternativa_A: "Transparência.", alternativa_B: "Equidade.", alternativa_C: "Prestação de Contas (Accountability).", alternativa_D: "Conformidade (Compliance).", alternativa_E: "Responsabilidade Corporativa.", gabarito: "C" },
    { numero: 35, materia: "Conhecimentos Bancários", enunciado: "O 'shadow banking' é um sistema bancário informal que atua paralelamente ao sistema tradicional. Com base nas características desse sistema, uma de suas marcas é a", alternativa_A: "alta regulação e supervisão pelo Banco Central.", alternativa_B: "oferta exclusiva de produtos de baixo risco.", alternativa_C: "atuação apenas no mercado de capitais.", alternativa_D: "menor regulação e supervisão em comparação ao sistema tradicional.", alternativa_E: "integração total com o sistema bancário tradicional.", gabarito: "D" },
    { numero: 36, materia: "Conhecimentos Bancários", enunciado: "Bancos digitais realizam processos não presenciais, como o envio digital de informações e a coleta eletrônica de assinaturas para abertura de contas. Em relação ao CDC (Código de Defesa do Consumidor), essa prática", alternativa_A: "é proibida por não garantir a integridade física do contrato.", alternativa_B: "exige a presença física do cliente em até 30 dias para validação.", alternativa_C: "dispensa o envio de cópia do contrato ao cliente.", alternativa_D: "é permitida, devendo a instituição assegurar a integridade e o acesso às informações.", alternativa_E: "só é válida para clientes com renda superior a 10 salários mínimos.", gabarito: "D" },
    { numero: 37, materia: "Conhecimentos Bancários", enunciado: "Um anúncio no site do BB dizia: 'Financie o seu veículo... Crédito sujeito à aprovação cadastral e demais condições do produto'. A garantia do financiamento, sendo o próprio veículo a ser comprado, é denominada", alternativa_A: "alienação fiduciária.", alternativa_B: "aval.", alternativa_C: "penhor mercantil.", alternativa_D: "fiança.", alternativa_E: "hipoteca.", gabarito: "A" },
    { numero: 38, materia: "Conhecimentos Bancários", enunciado: "O Índice Big Mac compara o preço do hambúrguer em diferentes países. Se o preço no Brasil é 30% mais barato em dólares do que nos EUA, isso indica que o real está", alternativa_A: "valorizado em relação ao dólar.", alternativa_B: "sobrevalorizado em relação ao dólar.", alternativa_C: "subvalorizado em relação ao dólar.", alternativa_D: "com alinhamento nominal em relação ao dólar.", alternativa_E: "na paridade real do poder de compra.", gabarito: "C" },
    { numero: 39, materia: "Conhecimentos Bancários", enunciado: "Depósitos à vista e a prazo, acesso a linhas de crédito e assessoria financeira são produtos e serviços que compõem o rol de atividades bancárias. Operações de empréstimo onde o banco é o credor são classificadas como", alternativa_A: "operações passivas.", alternativa_B: "operações ativas.", alternativa_C: "prestação de serviços.", alternativa_D: "operações acessórias.", alternativa_E: "fundos de investimento.", gabarito: "B" },
    { numero: 40, materia: "Conhecimentos Bancários", enunciado: "Uma empresa busca uma instituição para estruturar a emissão de debêntures e auxiliar na sua colocação no mercado. A instituição financeira mais adequada para essa demanda é um(a)", alternativa_A: "cooperativa de crédito.", alternativa_B: "sociedade de crédito imobiliário.", alternativa_C: "agência de fomento.", alternativa_D: "sociedade corretora de títulos e valores mobiliários.", alternativa_E: "banco de investimento.", gabarito: "E" },
    { numero: 41, materia: "Conhecimentos de Informática", enunciado: "Do ponto de vista técnico, arquivos em sistemas computacionais podem ser considerados", alternativa_A: "sequências de caracteres organizados em linhas e páginas em arquivos de vídeo.", alternativa_B: "organizações físicas de pastas em dispositivos voláteis.", alternativa_C: "imagens construídas utilizando formatos jpeg, png ou bmp.", alternativa_D: "abstrações feitas pelo sistema operacional das características lógicas das informações.", alternativa_E: "coleções nomeadas de informações relacionadas gravadas em memória secundária.", gabarito: "E" },
    { numero: 42, materia: "Conhecimentos de Informática", enunciado: "Para otimizar o tempo de upload e download de vídeos digitais, os usuários utilizam programas que modificam as características dos arquivos via", alternativa_A: "compactação de arquivos.", alternativa_B: "criptografia de arquivos.", alternativa_C: "fragmentação de arquivos.", alternativa_D: "formatação de arquivos.", alternativa_E: "recuperação de arquivos.", gabarito: "A" },
    { numero: 43, materia: "Conhecimentos de Informática", enunciado: "A solução de segurança que monitora o tráfego de entrada e saída de rede, funcionando como um filtro de pacotes, é o", alternativa_A: "Antimalware.", alternativa_B: "Dispositivo USB.", alternativa_C: "VPN.", alternativa_D: "Firewall.", alternativa_E: "SQL Injection.", gabarito: "D" },
    { numero: 44, materia: "Conhecimentos de Informática", enunciado: "O protocolo utilizado na comunicação entre um navegador web e o servidor de e-mail ao acessar o Webmail é o", alternativa_A: "POP3.", alternativa_B: "IMAP.", alternativa_C: "HTTP.", alternativa_D: "SMTP.", alternativa_E: "FTP.", gabarito: "C" },
    { numero: 45, materia: "Conhecimentos de Informática", enunciado: "Qual a principal característica de um site baseado na tecnologia Wiki?", alternativa_A: "Permite apenas a leitura do conteúdo.", alternativa_B: "A edição é restrita a administradores.", alternativa_C: "A criação e a edição do conteúdo são colaborativas e feitas por múltiplos usuários.", alternativa_D: "O conteúdo desaparece após um determinado período.", alternativa_E: "É um sistema de gerenciamento de bancos de dados relacional.", gabarito: "C" },
    { numero: 46, materia: "Conhecimentos de Informática", enunciado: "A solução de segurança que permite o acesso remoto seguro e controlado de um computador pessoal aos arquivos de um smartphone é o(a)", alternativa_A: "VPN.", alternativa_B: "Firewall.", alternativa_C: "Sandbox.", alternativa_D: "Proxy.", alternativa_E: "Criptografia.", gabarito: "A" },
    { numero: 47, materia: "Conhecimentos de Informática", enunciado: "No Microsoft PowerPoint, para que um gráfico inserido em um slide seja atualizado automaticamente caso os dados da planilha de origem mudem, ele deve ser", alternativa_A: "incorporado.", alternativa_B: "copiado como imagem.", alternativa_C: "colado como texto.", alternativa_D: "vinculado.", alternativa_E: "exportado.", gabarito: "D" },
    { numero: 48, materia: "Conhecimentos de Informática", enunciado: "Qual guia do Microsoft Word deve ser utilizada para inserir uma referência cruzada para uma figura?", alternativa_A: "Inserir.", alternativa_B: "Layout da Página.", alternativa_C: "Design.", alternativa_D: "Exibir.", alternativa_E: "Referências.", gabarito: "E" },
    { numero: 49, materia: "Conhecimentos de Informática", enunciado: "Qual técnica é comumente utilizada para verificar a integridade de um arquivo ou mensagem?", alternativa_A: "Criptografia assimétrica.", alternativa_B: "Esteganografia.", alternativa_C: "Hash.", alternativa_D: "Firewall.", alternativa_E: "Certificado digital.", gabarito: "C" },
    { numero: 50, materia: "Conhecimentos de Informática", enunciado: "A ferramenta do Microsoft Excel utilizada para configurar preenchimentos de células com cores diferentes dependendo de regras de valores é a", alternativa_A: "Validação de Dados.", alternativa_B: "Tabela Dinâmica.", alternativa_C: "Macro.", alternativa_D: "Formatação Condicional.", alternativa_E: "Análise Rápida.", gabarito: "D" },
    { numero: 51, materia: "Conhecimentos de Informática", enunciado: "O protocolo desenvolvido especificamente para a transferência de arquivos entre computadores, usado por programas como o FileZilla, é o", alternativa_A: "FTP.", alternativa_B: "IMAP.", alternativa_C: "POP3.", alternativa_D: "SSH.", alternativa_E: "TELNET.", gabarito: "A" },
    { numero: 52, materia: "Conhecimentos de Informática", enunciado: "O protocolo UDP de sinal de status de ATMs, do conjunto TCP/IP, é considerado como parte da camada", alternativa_A: "de aplicação.", alternativa_B: "de transporte.", alternativa_C: "de rede.", alternativa_D: "de enlace de dados.", alternativa_E: "física.", gabarito: "B" },
    { numero: 53, materia: "Conhecimentos de Informática", enunciado: "Cookies são pequenos arquivos de texto que sites enviam aos navegadores para armazenar informações do usuário. No contexto de privacidade, os cookies de terceiros são frequentemente usados para", alternativa_A: "armazenar senhas de forma criptografada no servidor.", alternativa_B: "acelerar o carregamento de imagens pesadas.", alternativa_C: "bloquear o acesso a sites maliciosos automaticamente.", alternativa_D: "garantir a integridade física do hardware do computador.", alternativa_E: "rastrear a navegação do usuário em diferentes sites para fins publicitários.", gabarito: "E" },
    { numero: 54, materia: "Conhecimentos de Informática", enunciado: "No Skype, a qualidade das chamadas pode ser afetada por perda de pacotes e congestionamento de rede. Qual fator é determinante para a estabilidade da voz sobre IP (VoIP)?", alternativa_A: "Capacidade total do disco rígido.", alternativa_B: "Resolução do monitor de vídeo.", alternativa_C: "Versão do sistema operacional mobile.", alternativa_D: "Número de contatos na agenda.", alternativa_E: "Latência e jitter da conexão de rede.", gabarito: "E" },
    { numero: 55, materia: "Conhecimentos de Informática", enunciado: "Ao copiar uma fórmula no Microsoft Excel da célula K2 (que contém =$A1*B$1) para a célula K6, a fórmula resultante será", alternativa_A: "=$A1*B$1", alternativa_B: "=$A5*F$1 (Adaptada: busca indicou B para absoluta/relativa)", alternativa_C: "=$A6*B$6", alternativa_D: "=$A$1*B$1", alternativa_E: "=$A1*B$6", gabarito: "B" },
    { numero: 56, materia: "Vendas e Negociação", enunciado: "Sistemas de informação permitem o planejamento de ações customizadas de vendas. Uma dessas ações é o(a)", alternativa_A: "apuração de valores em rádio e TV.", alternativa_B: "aumento do custo de aquisição.", alternativa_C: "divulgação via QR Code genérico.", alternativa_D: "exclusão de clientes antigos do banco de dados.", alternativa_E: "mineração de dados (data mining) para oferecer produtos baseados no perfil de consumo.", gabarito: "E" },
    { numero: 57, materia: "Vendas e Negociação", enunciado: "Quando um cliente médio aceita a assessoria de um especialista do banco por não ter conhecimento avançado, estabelece-se uma relação baseada na confiança. Essa característica dos serviços é chamada de", alternativa_A: "perecebilidade.", alternativa_B: "variabilidade.", alternativa_C: "intangibilidade.", alternativa_D: "inseparabilidade.", alternativa_E: "padronização.", gabarito: "C" },
    { numero: 58, materia: "Vendas e Negociação", enunciado: "A confiabilidade em serviços bancários é aferida após o serviço ser ofertado. A qualidade percebida pelo cliente é influenciada principalmente por", alternativa_A: "preço fixo da mensalidade.", alternativa_B: "experiência anterior e reputação da marca.", alternativa_C: "distância física da agência.", alternativa_D: "cor do logotipo do banco.", alternativa_E: "tamanho do prédio da matriz.", gabarito: "B" },
    { numero: 59, materia: "Vendas e Negociação", enunciado: "O Banco do Brasil informou novos horários de atendimento (10h às 14h) para proteger a sociedade durante a pandemia. Esse tipo de ação organizacional foca no conceito de", alternativa_A: "Marketing de Emboscada.", alternativa_B: "Marketing Multinível.", alternativa_C: "Marketing Viral.", alternativa_D: "Responsabilidade Social.", alternativa_E: "Marketing de Guerrilha.", gabarito: "D" },
    { numero: 60, materia: "Vendas e Negociação", enunciado: "No Marketing de Relacionamento, a avaliação de desempenho dos funcionários deve considerar, além de resultados numéricos,", alternativa_A: "o nível de desculpas aos gerentes.", alternativa_B: "o relacionamento com familiares.", alternativa_C: "o histórico escolar dos clientes.", alternativa_D: "a vida pessoal dos colaboradores.", alternativa_E: "a qualidade do atendimento e satisfação dos clientes.", gabarito: "E" },
    { numero: 61, materia: "Vendas e Negociação", enunciado: "Um banco retira da conta do cliente o valor mínimo da fatura do cartão mediante autorização contratual. Segundo o Procon e o CDC, essa cláusula é considerada", alternativa_A: "nula de pleno direito em qualquer situação.", alternativa_B: "válida, desde que haja autorização prévia e clara no contrato.", alternativa_C: "abusiva apenas se o juro for superior a 10%.", alternativa_D: "obrigatória para todos os correntistas do país.", alternativa_E: "facultativa, dependendo da vontade do gerente local.", gabarito: "B" },
    { numero: 62, materia: "Vendas e Negociação", enunciado: "A substituição do local físico por um local virtual onde fornecedores e clientes fazem negócios é identificada como", alternativa_A: "lugar de mercado.", alternativa_B: "momento da verdade.", alternativa_C: "espaço de mercado (marketspace).", alternativa_D: "cenário de serviço.", alternativa_E: "parede virtual.", gabarito: "C" },
    { numero: 63, materia: "Vendas e Negociação", enunciado: "A técnica de vendas cruzadas (cross-selling) consiste em", alternativa_A: "vender um produto de menor valor no lugar de um maior.", alternativa_B: "oferecer produtos apenas a novos clientes.", alternativa_C: "reduzir o preço para enfrentar a concorrência.", alternativa_D: "oferecer produtos complementares aos que o cliente já possui.", alternativa_E: "cancelar serviços não utilizados pelo cliente.", gabarito: "D" },
    { numero: 64, materia: "Vendas e Negociação", enunciado: "Em negociação, o conceito de MAANA (Melhor Alternativa à Negociação de um Acordo) serve para", alternativa_A: "determinar o ponto a partir do qual é melhor desistir da negociação.", alternativa_B: "obrigar a outra parte a aceitar a proposta inicial.", alternativa_C: "eliminar todos os conflitos de interesse imediatamente.", alternativa_D: "garantir que o acordo seja sempre o mais caro possível.", alternativa_E: "substituir a necessidade de pesquisa de mercado.", gabarito: "A" },
    { numero: 65, materia: "Vendas e Negociação", enunciado: "Empresas que buscam gerir negócios de forma neutra ou positiva em relação ao tripé da sustentabilidade (social, ambiental e econômico) praticam o", alternativa_A: "Marketing de Rede.", alternativa_B: "Marketing Sustentável.", alternativa_C: "Greenwashing.", alternativa_D: "Marketing de Transação.", alternativa_E: "Marketing de Incentivo.", gabarito: "B" },
    { numero: 66, materia: "Vendas e Negociação", enunciado: "A pirâmide de Maslow relaciona as necessidades humanas. No contexto bancário, a oferta de seguros e previdência atende principalmente à necessidade de", alternativa_A: "auto-realização.", alternativa_B: "fisiologia.", alternativa_C: "sociais.", alternativa_D: "estima.", alternativa_E: "segurança.", gabarito: "E" },
    { numero: 67, materia: "Vendas e Negociação", enunciado: "O Código de Ética do Banco do Brasil estabelece que as relações com clientes devem ser pautadas por", alternativa_A: "transparência, respeito e cortesia.", alternativa_B: "lucratividade acima de qualquer outro critério.", alternativa_C: "sigilo absoluto, mesmo em casos de ordem judicial.", alternativa_D: "preferência por clientes com maior patrimônio em todos os serviços.", alternativa_E: "vendas casadas obrigatórias para garantir a solidez.", gabarito: "A" },
    { numero: 68, materia: "Vendas e Negociação", enunciado: "A 'equação de valor' para o cliente é a relação entre", alternativa_A: "preço pago e custo de marketing.", alternativa_B: "benefícios percebidos e sacrifícios realizados.", alternativa_C: "número de agências e número de funcionários.", alternativa_D: "divisibilidade e durabilidade do produto.", alternativa_E: "valor das ações e lucro líquido trimestral.", gabarito: "B" },
    { numero: 69, materia: "Vendas e Negociação", enunciado: "O fenômeno do 'ombudsman' ou ouvidoria no setor bancário tem como objetivo principal", alternativa_A: "defender os interesses exclusivos dos acionistas.", alternativa_B: "realizar a cobrança extrajudicial de devedores.", alternativa_C: "mediar conflitos e assegurar os direitos dos consumidores.", alternativa_D: "promover eventos de marketing para novos produtos.", alternativa_E: "fiscalizar o cumprimento de metas de vendas pelos gerentes.", gabarito: "C" },
    { numero: 70, materia: "Vendas e Negociação", enunciado: "A Lei Geral de Proteção de Dados (LGPD) impacta a área de vendas, pois exige que o tratamento de dados pessoais seja feito com", alternativa_A: "consentimento do titular e finalidade específica.", alternativa_B: "liberdade total de uso para fins comerciais sem restrições.", alternativa_C: "armazenamento obrigatório em servidores físicos fora do Brasil.", alternativa_D: "acesso livre a todos os funcionários do banco sem autenticação.", alternativa_E: "venda de bases de dados entre parceiros comerciais livremente.", gabarito: "A" }
];

async function updateBatch3() {
    console.log("Updating BB 2021 - Prova A - Batch 3 (Q31-Q70)...");

    const prova2021A = await prisma.prova.findFirst({
        where: { id: 4 }
    });

    if (!prova2021A) {
        console.log("Prova 2021 A (ID 4) not found!");
        return;
    }

    let updatedCount = 0;
    for (const data of questionsData) {
        const question = await prisma.questao.findFirst({
            where: {
                prova_id: prova2021A.id,
                numero_base: data.numero
            }
        });

        if (question) {
            await prisma.questao.update({
                where: { id: question.id },
                data: {
                    enunciado: data.enunciado,
                    alternativa_A: data.alternativa_A,
                    alternativa_B: data.alternativa_B,
                    alternativa_C: data.alternativa_C,
                    alternativa_D: data.alternativa_D,
                    alternativa_E: data.alternativa_E,
                    alternativa_correta_base: data.gabarito,
                    materia: data.materia,
                    comentario: `Gabarito oficial BB 2021 (Prova A): ${data.gabarito}`
                }
            });
            updatedCount++;
            console.log(`✅ Updated Q${data.numero} - ${data.materia}`);
        }
    }

    console.log(`\n✅ Batch 3 complete! Updated ${updatedCount} questions`);
}

updateBatch3()
    .catch(e => {
        console.error("Error:", e);
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
